apiVersion: v1
kind: Service
metadata:
  name: service-dockerhub-deploy-2
  labels:
    run: service-dockerhub-deploy
spec:
  type: LoadBalancer
  selector:
    run: dockerhub-deploy
  ports:
  - name: http
    port: 8080
    targetPort: 8000
    protocol: TCP
